# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
    end

    config.vm.define "nodeA" do |nodeA|
        nodeA.vm.box = "ubuntu/trusty64"
        nodeA.vm.network "private_network", ip: "37.51.23.10"
        nodeA.vm.network "forwarded_port", guest: 8088, host: 8088
        nodeA.vm.network "forwarded_port", guest: 50070, host: 50070
        nodeA.vm.hostname = "master"
        if Vagrant.has_plugin?("vagrant-cachier")
            nodeA.cache.scope = :box
        end
        nodeA.vm.provision "shell", inline: <<-SHELL

            # !!! YOU NEED TO REPLACE HERE CORRECT IP ADDRESS !!!
            sudo echo "37.51.23.10 master" >> /etc/hosts
            sudo echo "37.51.23.11 slave" >> /etc/hosts

            # Update VM to the latest binaries from distribution
            # package.
            sudo apt-get update && sudo apt-get upgrade -y
            sudo apt-get install -y vim telnet wget curl htop nmon dos2unix

            dos2unix -q /vagrant/*.sh && dos2unix -q /vagrant/scripts/* && dos2unix -q /vagrant/config/* && dos2unix -q /vagrant/config/.bashrc

            # Installing and configuring java.
            cp /vagrant/install_java.sh .
            ./install_java.sh

            # Passwordless ssh communication between two virtual nodes.
            su vagrant -c "ssh-keygen -t rsa -P '' -f /home/vagrant/.ssh/id_rsa"
            mkdir -p /vagrant/files/ssh/
            cp /home/vagrant/.ssh/id_rsa.pub /vagrant/files/ssh/master.pub
            cp /vagrant/after_startup.sh /home/vagrant/.

            # TODO: In order to complete Hadoop configuration you have to
            # provide here set of Linux shell commands which completes
            # instalation and configuration of Hadoop cluster.

            # !!! Fill your commands here !!!

            cp /vagrant/scripts/* .
            source ./install-hadoop.sh

            ./setup-master.sh
        SHELL
    end

    config.vm.define "nodeB" do |nodeB|
        nodeB.vm.box = "ubuntu/trusty64"
        nodeB.vm.network "private_network", ip: "37.51.23.11"
        nodeB.vm.network "forwarded_port", guest: 8088, host: 9088
        nodeB.vm.hostname = "slave"
        if Vagrant.has_plugin?("vagrant-cachier")
            nodeB.cache.scope = :box
        end
        nodeB.vm.provision "shell", inline: <<-SHELL
            # !!! YOU NEED TO REPLACE HERE CORRECT IP ADDRESS !!!
            sudo echo "37.51.23.10 master" >> /etc/hosts
            sudo echo "37.51.23.11 slave" >> /etc/hosts

            # Update VM to the latest binaries from distribution
            # package.
            sudo apt-get update && sudo apt-get upgrade -y
            sudo apt-get install -y vim telnet wget curl htop nmon dos2unix

            dos2unix -q /vagrant/*.sh && dos2unix -q /vagrant/scripts/* && dos2unix -q /vagrant/config/* && dos2unix -q /vagrant/config/.bashrc

            # Installing and configuring java.
            cp /vagrant/install_java.sh .
            ./install_java.sh

            # Passwordless ssh communication between two virtual nodes.
            su vagrant -c "ssh-keygen -t rsa -P '' -f /home/vagrant/.ssh/id_rsa"
            mkdir -p /vagrant/files/ssh/
            cp /home/vagrant/.ssh/id_rsa.pub /vagrant/files/ssh/slave.pub
            cp /vagrant/after_startup.sh /home/vagrant/.

            # TODO: In order to complete Hadoop configuration you have to
            # provide here set of Linux shell commands which completes
            # instalation and configuration of Hadoop cluster.

            # !!! Fill your commands here !!!
            
            cp /vagrant/scripts/* .
            source ./install-hadoop.sh

        SHELL
    end
end
