export JAVA_HOME="/usr/lib/jvm/jdk1.8.0_77"

export HADOOP_PREFIX="/home/vagrant/hadoop-2.7.2"
export HADOOP_HOME=$HADOOP_PREFIX
export HADOOP_COMMON_HOME=$HADOOP_PREFIX
export HADOOP_CONF_DIR=$HADOOP_PREFIX/etc/hadoop
export HADOOP_HDFS_HOME=$HADOOP_PREFIX
export HADOOP_MAPRED_HOME=$HADOOP_PREFIX
export HADOOP_YARN_HOME=$HADOOP_PREFIX

export PATH=$PATH:$JAVA_HOME/bin:$HADOOP_PREFIX:$HADOOP_PREFIX/sbin:$HADOOP_PREFIX/bin
export SPARK_DIST_CLASSPATH=$(hadoop classpath)
